image: php:7.4

stages:
  - deploy

before_script:
  - apt-get update && apt-get install -y openssh-client git
  - mkdir -p ~/.ssh && chmod 700 ~/.ssh
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan -H "69.62.89.61" >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

deploy:
  stage: deploy
  only:
    - main
script:
- ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@69.62.89.61 "cd /var/www/html/v2 && 
# Verificar se composer está instalado e usar diretamente
composer install --no-dev --optimize-autoloader && 

# Verificar o arquivo .env para garantir que as credenciais do banco de dados estejam corretas
# Substitua DB_USERNAME e DB_PASSWORD com as credenciais corretas se necessário
# sed -i 's/DB_USERNAME=forge/DB_USERNAME=seu_usuario_correto/' .env && 
# sed -i 's/DB_PASSWORD=/DB_PASSWORD=sua_senha_correta/' .env && 

# Executar as migrações e limpar caches
php artisan config:cache && 
php artisan migrate --force && 
sudo systemctl reload php7.4-fpm && 
sudo systemctl reload nginx"