stages:
  - deploy

deploy:
  stage: deploy
  image: alpine:latest
  only:
    - main
  before_script:
  - ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts

script:
  - rsync -avz --delete "$CI_PROJECT_DIR"/ root@"$DEPLOY_HOST":/var/www/html/v2/
  - ssh root@"$DEPLOY_HOST" bash -lc "
      cd /var/www/html/v2 &&
      composer install --no-dev --optimize-autoloader &&
      php artisan migrate --force &&
      php artisan config:cache &&
      php artisan route:cache &&
      php artisan view:cache &&
      systemctl reload php7.4-fpm &&
      systemctl reload nginx
