stages:
  - deploy

deploy_to_vps:
  stage: deploy
  image: alpine:latest

  before_script:
    - apk add --no-cache openssh-client rsync bash
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo ">> DEPLOY_USER=[$DEPLOY_USER]"
    - ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts || true

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

  script:
    - rsync -av --delete "$CI_PROJECT_DIR/" "$DEPLOY_USER@$DEPLOY_HOST:/var/www/html/v2/"
    - |
      ssh $DEPLOY_USER@$DEPLOY_HOST << 'EOF'
      cd /var/www/html/v2
      composer install --no-dev --optimize-autoloader
      php artisan optimize:clear
      sudo systemctl reload php7.4-fpm
      sudo systemctl reload nginx
      EOF
