image: php:7.4

stages:
  - deploy

before_script:
  # 1) instala SSH e Git
  - apt-get update && apt-get install -y openssh-client git

  # 2) cria ~/.ssh e grava a chave PEM
  - mkdir -p ~/.ssh && chmod 700 ~/.ssh
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa

  # 3) adiciona host sem prompt
  - ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

deploy_production:
  stage: deploy
  only:
    - main
  script:
    # Use root no SSH (ou outro user correto)
    - |
      ssh -i ~/.ssh/id_rsa \
          -o StrictHostKeyChecking=no \
          root@$DEPLOY_HOST "\
            cd $DEPLOY_PATH && \
            git fetch origin main && git reset --hard origin/main && \
            composer install --no-dev --optimize-autoloader && \
            php artisan migrate --force && \
            php artisan config:clear && php artisan route:clear && \
            php artisan view:clear && php artisan config:cache && \
            php artisan route:cache && php artisan view:cache && \
            sudo systemctl reload php7.4-fpm && sudo systemctl reload nginx \
          "
