stages:
  - deploy

deploy:
  stage: deploy
  image: alpine:latest
  only:
    - principal
  before_script:
    - apk add --no-cache openssh-client rsync bash
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 69.62.89.61 >> ~/.ssh/known_hosts
  script:
    - rsync -avz --delete "$CI_PROJECT_DIR"/ hotboys_user@69.62.89.61:/var/www/html/v2/
    - ssh hotboys_user@69.62.89.61 bash -lc "
        cd /var/www/html/v2 &&
        composer install --no-dev --optimize-autoloader &&
        php artisan migrate --force &&
        php artisan config:cache &&
        php artisan route:cache &&
        php artisan view:cache &&
        sudo systemctl reload php7.4-fpm &&
        sudo systemctl reload nginx
      "
