deploy_prod:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client git
    - mkdir -p ~/.ssh
    - cp "$SSH_PRIVATE_KEY" ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 69.62.89.61 >> ~/.ssh/known_hosts

  script:
    - ssh root@69.62.89.61 << 'EOF'
        cd /var/www/html/v2
        git pull origin main
        composer install --no-dev --optimize-autoloader
        php artisan view:clear cache:clear config:clear route:clear
        systemctl reload php7.4-fpm
      EOF

  only:
    - main
