image: php:7.4

stages:
  - deploy

before_script:
  # 1) debug da chave
  - echo ">>> bytes de SSH_KEY_B64:" && echo "$SSH_KEY_B64" | wc -c
  - echo ">>> linhas após decodificar:" && echo "$SSH_KEY_B64" | base64 -d > ~/.ssh/id_rsa && wc -l ~/.ssh/id_rsa
  - echo ">>> head/tail:" && head -n1 ~/.ssh/id_rsa && tail -n1 ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa

  # 2) instala SSH e Git
  - apt-get update && apt-get install -y openssh-client git

  # 3) evita prompt de host
  - mkdir -p ~/.ssh && ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts

deploy_production:
  stage: deploy
  only:
    - main
  script:
    - |
      ssh -i ~/.ssh/id_rsa \
          -o StrictHostKeyChecking=no \
          root@$DEPLOY_HOST "\
            cd $DEPLOY_PATH && \
            git fetch origin main && git reset --hard origin/main && \
            composer install --no-dev --optimize-autoloader && \
            php artisan migrate --force && \
            php artisan config:clear && php artisan route:clear && php artisan view:clear && \
            php artisan config:cache && php artisan route:cache && php artisan view:cache && \
            sudo systemctl reload php7.4-fpm && sudo systemctl reload nginx \
          "
