deploy_to_vps:
  stage: deploy
  tags:
    - vps-hotboys
  script:
    - rsync -av --delete "$CI_PROJECT_DIR/" /var/www/html/v2/
    - cd /var/www/html/v2
    - composer install --no-dev --optimize-autoloader
    - php artisan optimize:clear
    # Agora com sudo
    - sudo systemctl reload php7.4-fpm
  when: manual